"use strict";
/**
 * Static PWA build for phones: dist/pwa/ is the app/ folder plus the daemon's API
 * responses frozen to api/*.json, a service worker for offline use at the range,
 * and a flag (window.GOLFBITS_STATIC) that makes app.js read those files and keep
 * progress in the phone's localStorage instead of POSTing to the daemon.
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { ROOT, APP_DIR, PLAYBOOK_FILE, PLAN_FILE } = require("./paths");
const { loadBits } = require("./content");
const { readProgress } = require("./progress");
const { resolveConfig } = require("./conf");

const DIST_DIR = path.join(ROOT, "dist", "pwa");

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const name of fs.readdirSync(from)) {
    if (name.startsWith(".")) continue;
    const a = path.join(from, name), b = path.join(to, name);
    if (fs.statSync(a).isDirectory()) copyDir(a, b);
    else fs.copyFileSync(a, b);
  }
}

function listFiles(dir, base = dir) {
  return fs.readdirSync(dir).flatMap(name => {
    const full = path.join(dir, name);
    return fs.statSync(full).isDirectory() ? listFiles(full, base) : [path.relative(base, full).split(path.sep).join("/")];
  });
}

const STATIC_HEAD = `<script>window.GOLFBITS_STATIC = true;</script>`;
const SW_REGISTER = `<script>
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", function () { navigator.serviceWorker.register("/sw.js").catch(function () {}); });
  }
</script>`;

function injectHtml(file) {
  let html = fs.readFileSync(file, "utf8");
  if (!html.includes("</head>") || !html.includes("</body>")) throw new Error(`${path.basename(file)} has no </head> or </body>`);
  html = html.replace("</head>", `${STATIC_HEAD}\n</head>`).replace("</body>", `${SW_REGISTER}\n</body>`);
  fs.writeFileSync(file, html);
}

function serviceWorker(version, files) {
  const precache = ["/", ...files.filter(f => f !== "sw.js").map(f => "/" + f)];
  return `/* golfbits service worker — generated by lib/pwa.js, version ${version} */
const CACHE = "golfbits-${version}";
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith("golfbits-") && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Network first (fresh content when there's signal), cache fallback (works on the range with none).
self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) {
    // Google Fonts etc.: cache whatever we get, serve it offline.
    e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
      const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); return res;
    }).catch(() => hit)));
    return;
  }
  // A 3-second cap so weak range signal doesn't leave the screen blank.
  const network = new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error("slow")), 3000);
    fetch(req).then(r => { clearTimeout(t); resolve(r); }, err => { clearTimeout(t); reject(err); });
  });
  e.respondWith(network.then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  }).catch(() => caches.match(req, { ignoreSearch: true })
    .then(hit => hit || fetch(req))
    .catch(() => caches.match("/"))));
});
`;
}

/** Build dist/pwa. Returns { outDir, files, version }. */
function buildPwa({ outDir = DIST_DIR, quiet = false } = {}) {
  // Range Book page is generated from content/range; rebuild so app/range.html is current.
  const { buildRange } = require("../scripts/build-range");
  buildRange();

  fs.rmSync(outDir, { recursive: true, force: true });
  copyDir(APP_DIR, outDir);

  const api = path.join(outDir, "api");
  fs.mkdirSync(api, { recursive: true });
  const c = resolveConfig();
  const write = (name, obj) => fs.writeFileSync(path.join(api, name + ".json"), JSON.stringify(obj));
  write("bits", loadBits().map(({ __file, ...bit }) => bit));
  write("progress", readProgress());
  write("config", { agent: c.provider, learner: c.raw.learner.name, batchSize: c.batchSize, static: true });
  write("playbook", { markdown: fs.existsSync(PLAYBOOK_FILE) ? fs.readFileSync(PLAYBOOK_FILE, "utf8") : "" });
  if (fs.existsSync(PLAN_FILE)) write("plan", JSON.parse(fs.readFileSync(PLAN_FILE, "utf8")));

  for (const page of ["index.html", "range.html"]) {
    const f = path.join(outDir, page);
    if (fs.existsSync(f)) injectHtml(f);
  }

  const files = listFiles(outDir).sort();
  const h = crypto.createHash("sha256");
  for (const f of files) h.update(f).update(fs.readFileSync(path.join(outDir, f)));
  const version = h.digest("hex").slice(0, 12);
  fs.writeFileSync(path.join(outDir, "sw.js"), serviceWorker(version, files));
  const all = listFiles(outDir).sort();
  if (!quiet) console.log(`PWA built: ${path.relative(ROOT, outDir)}/ (${all.length} files, version ${version})`);
  return { outDir, files: all, version };
}

module.exports = { buildPwa, DIST_DIR, listFiles };
